INSERT INTO pima.attendances AS t (
  id,
  farmer_id,
  training_session_id,
  date_attended,
  submission_id,
  status,
  created_at,
  updated_at,
  created_by_id,
  last_updated_by_id,
  from_sf,
  sf_id,
  is_deleted,
  deleted_at
) VALUES (
  :id,
  :farmer_id,
  :training_session_id,
  :date_attended,
  :submission_id,
  :status,
  :created_at,
  :updated_at,
  :system_user,
  :system_user,
  TRUE,
  :sf_id,
  :is_deleted,
  :deleted_at
)
ON CONFLICT (sf_id) DO UPDATE SET
  farmer_id          = EXCLUDED.farmer_id,
  training_session_id= EXCLUDED.training_session_id,
  date_attended      = EXCLUDED.date_attended,
  submission_id      = EXCLUDED.submission_id,
  status             = EXCLUDED.status,
  created_at         = LEAST(t.created_at, EXCLUDED.created_at),
  updated_at         = EXCLUDED.updated_at,
  last_updated_by_id = EXCLUDED.last_updated_by_id,
  from_sf            = TRUE,
  sf_id              = EXCLUDED.sf_id,
  is_deleted         = EXCLUDED.is_deleted,
  deleted_at         = EXCLUDED.deleted_at;
