INSERT INTO pima.project_staff_roles (
    id,
    staff_id,
    project_id,
    tns_id,
    role,
    status,
    commcare_location_id,
    commcare_case_id,
    created_at,
    updated_at,
    send_to_commcare_status,
    from_sf,
    sf_id,
    is_deleted,
    deleted_at,
    send_to_commcare,
    created_by_id,
    last_updated_by_id
) VALUES (
    :id,
    :staff_id,
    :project_id,
    :tns_id,
    :role,
    :status,
    NULL,
    :commcare_case_id,
    :created_at,
    :updated_at,
    'Pending',
    false,
    NULL,
    false,
    NULL,
    false,
    :system_user,
    :system_user
)
ON CONFLICT (id) DO UPDATE SET
    staff_id = EXCLUDED.staff_id,
    project_id = EXCLUDED.project_id,
    tns_id = EXCLUDED.tns_id,
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at,
    last_updated_by_id = EXCLUDED.last_updated_by_id;