INSERT INTO pima.users (
    id,
    first_name,
    middle_name,
    last_name,
    email,
    username,
    password,
    created_at,
    updated_at,
    tns_id,
    phone_number,
    job_title,
    user_role,
    status,
    from_sf,
    sf_id,
    is_deleted,
    deleted_at,
    commcare_mobile_worker_id,
    manager_id,
    created_by_id,
    last_updated_by_id
) VALUES (
    :id,
    :first_name,
    :middle_name,
    :last_name,
    :email,
    :username,
    :password,
    :created_at,
    :updated_at,
    :tns_id,
    :phone_number,
    :job_title,
    :user_role,
    :status,
    false,
    :sf_id,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
)
ON CONFLICT (email) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    middle_name = EXCLUDED.middle_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    password = EXCLUDED.password,
    updated_at = EXCLUDED.updated_at,
    tns_id = EXCLUDED.tns_id,
    phone_number = EXCLUDED.phone_number,
    job_title = EXCLUDED.job_title,
    user_role = EXCLUDED.user_role,
    status = EXCLUDED.status,
    sf_id = EXCLUDED.sf_id;