INSERT INTO pima.farmers AS t (
  id,
  household_id,
  farmer_group_id,
  tns_id,
  commcare_case_id,
  first_name,
  middle_name,
  last_name,
  other_id,
  gender,
  age,
  phone_number,
  is_primary_household_member,
  status,
  send_to_commcare,
  send_to_commcare_status,
  status_notes,
  created_by_id,
  last_updated_by_id,
  from_sf,
  sf_id,
  is_deleted,
  deleted_at,
  created_at,
  updated_at
) VALUES (
  :id,
  :household_id,
  :farmer_group_id,
  :tns_id,
  :commcare_case_id,
  :first_name,
  :middle_name,
  :last_name,
  :other_id,
  :gender,
  :age,
  :phone_number,
  :is_primary_household_member,
  :status,
  :send_to_commcare,
  :send_to_commcare_status,
  :status_notes,
  :system_user,
  :system_user,
  TRUE,
  :sf_id,
  :is_deleted,
  :deleted_at,
  :created_at,
  :updated_at
)
ON CONFLICT ON CONSTRAINT farmers_sf_id_key DO UPDATE SET
  household_id                 = EXCLUDED.household_id,
  farmer_group_id              = EXCLUDED.farmer_group_id,
  tns_id                       = EXCLUDED.tns_id,
  commcare_case_id             = EXCLUDED.commcare_case_id,
  first_name                   = EXCLUDED.first_name,
  middle_name                  = EXCLUDED.middle_name,
  last_name                    = EXCLUDED.last_name,
  other_id                     = EXCLUDED.other_id,
  gender                       = EXCLUDED.gender,
  age                          = EXCLUDED.age,
  phone_number                 = EXCLUDED.phone_number,
  is_primary_household_member  = EXCLUDED.is_primary_household_member,
  status                       = EXCLUDED.status,
  send_to_commcare             = EXCLUDED.send_to_commcare,
  send_to_commcare_status      = EXCLUDED.send_to_commcare_status,
  status_notes                 = EXCLUDED.status_notes,
  last_updated_by_id           = EXCLUDED.last_updated_by_id,
  from_sf                      = TRUE,
  is_deleted                   = EXCLUDED.is_deleted,
  deleted_at                   = EXCLUDED.deleted_at,
  created_at                   = LEAST(t.created_at, EXCLUDED.created_at),
  updated_at                   = EXCLUDED.updated_at,
  sf_id                        = EXCLUDED.sf_id;
