INSERT INTO pima.households AS t (
  id,
  farmer_group_id,
  household_name,
  household_number,
  tns_id,
  commcare_case_id,
  number_of_trees,
  farm_size,
  sampled_for_fv_aa,
  farm_size_before,
  farm_size_after,
  farm_size_since,
  status,
  visited_for_fv_aa,
  fv_aa_sampling_round,
  created_by_id,
  last_updated_by_id,
  from_sf,
  sf_id,
  is_deleted,
  deleted_at,
  created_at,
  updated_at
) VALUES (
  :id,
  :farmer_group_id,
  :household_name,
  :household_number,
  :tns_id,
  :commcare_case_id,
  :number_of_trees,
  :farm_size,
  :sampled_for_fv_aa,
  :farm_size_before,
  :farm_size_after,
  :farm_size_since,
  :status,
  :visited_for_fv_aa,
  :fv_aa_sampling_round,
  :system_user,
  :system_user,
  TRUE,
  :sf_id,
  :is_deleted,
  :deleted_at,
  :created_at,
  :updated_at
)
ON CONFLICT ON CONSTRAINT households_sf_id_key DO UPDATE SET
  farmer_group_id       = EXCLUDED.farmer_group_id,
  household_name        = EXCLUDED.household_name,
  household_number      = EXCLUDED.household_number,
  tns_id                = EXCLUDED.tns_id,
  commcare_case_id      = EXCLUDED.commcare_case_id,
  number_of_trees       = EXCLUDED.number_of_trees,
  farm_size             = EXCLUDED.farm_size,
  sampled_for_fv_aa     = EXCLUDED.sampled_for_fv_aa,
  farm_size_before      = EXCLUDED.farm_size_before,
  farm_size_after       = EXCLUDED.farm_size_after,
  farm_size_since       = EXCLUDED.farm_size_since,
  status                = EXCLUDED.status,
  visited_for_fv_aa     = EXCLUDED.visited_for_fv_aa,
  fv_aa_sampling_round  = EXCLUDED.fv_aa_sampling_round,
  last_updated_by_id    = EXCLUDED.last_updated_by_id,
  from_sf               = TRUE,
  is_deleted            = EXCLUDED.is_deleted,
  deleted_at            = EXCLUDED.deleted_at,
  created_at            = LEAST(t.created_at, EXCLUDED.created_at),
  updated_at            = EXCLUDED.updated_at,
  sf_id                 = EXCLUDED.sf_id;
