MERGE INTO pima.observations AS t
USING (
  SELECT 
    CAST(:id AS UUID) AS id,
    CAST(:submission_id AS VARCHAR) AS submission_id,
    CAST(:observer_id AS UUID) AS observer_id,
    CAST(:trainer_id AS UUID) AS trainer_id,
    CAST(:farmer_group_id AS UUID) AS farmer_group_id,
    CAST(:training_session_id AS UUID) AS training_session_id,
    CAST(:observation_date AS DATE) AS observation_date,
    CAST(:location_gps_latitude AS NUMERIC) AS location_gps_latitude,
    CAST(:location_gps_longitude AS NUMERIC) AS location_gps_longitude,
    CAST(:location_gps_altitude AS NUMERIC) AS location_gps_altitude,
    CAST(:female_attendees AS INTEGER) AS female_attendees,
    CAST(:male_attendees AS INTEGER) AS male_attendees,
    CAST(:total_attendees AS INTEGER) AS total_attendees,
    CAST(:comments AS TEXT) AS comments,
    CAST(:observation_type AS pima.observation_type_enum) AS observation_type,
    CAST(:created_at AS TIMESTAMP) AS created_at,
    CAST(:updated_at AS TIMESTAMP) AS updated_at,
    CAST(:system_user AS UUID) AS system_user,
    CAST(:sf_id AS VARCHAR) AS sf_id,
    CAST(:is_deleted AS BOOLEAN) AS is_deleted,
    CAST(:deleted_at AS TIMESTAMP) AS deleted_at
) AS s
ON t.sf_id = s.sf_id OR t.submission_id = s.submission_id
WHEN MATCHED THEN
  UPDATE SET
    submission_id          = s.submission_id,
    observer_id            = s.observer_id,
    trainer_id             = s.trainer_id,
    farmer_group_id        = s.farmer_group_id,
    training_session_id    = s.training_session_id,
    observation_date       = s.observation_date,
    location_gps_latitude  = s.location_gps_latitude,
    location_gps_longitude = s.location_gps_longitude,
    location_gps_altitude  = s.location_gps_altitude,
    female_attendees       = s.female_attendees,
    male_attendees         = s.male_attendees,
    total_attendees        = s.total_attendees,
    comments               = s.comments,
    observation_type       = s.observation_type,
    updated_at             = s.updated_at,
    last_updated_by_id     = s.system_user,
    from_sf                = TRUE,
    is_deleted             = s.is_deleted,
    deleted_at             = s.deleted_at,
    sf_id                  = s.sf_id
WHEN NOT MATCHED THEN
  INSERT (
    id,
    submission_id,
    observer_id,
    trainer_id,
    farmer_group_id,
    training_session_id,
    observation_date,
    location_gps_latitude,
    location_gps_longitude,
    location_gps_altitude,
    female_attendees,
    male_attendees,
    total_attendees,
    comments,
    observation_type,
    created_at,
    updated_at,
    created_by_id,
    last_updated_by_id,
    from_sf,
    sf_id,
    is_deleted,
    deleted_at
  ) VALUES (
    s.id,
    s.submission_id,
    s.observer_id,
    s.trainer_id,
    s.farmer_group_id,
    s.training_session_id,
    s.observation_date,
    s.location_gps_latitude,
    s.location_gps_longitude,
    s.location_gps_altitude,
    s.female_attendees,
    s.male_attendees,
    s.total_attendees,
    s.comments,
    s.observation_type,
    s.created_at,
    s.updated_at,
    s.system_user,
    s.system_user,
    TRUE,
    s.sf_id,
    s.is_deleted,
    s.deleted_at
  );