INSERT INTO pima.observations AS t (
  id,
  submission_id,
  observer_id,
  trainer_id,
  farmer_group_id,
  training_session_id,
  observation_date,
  location_gps_latitude,
  location_gps_longitude,
  location_gps_altitude,
  female_attendees,
  male_attendees,
  total_attendees,
  comments,
  observation_type,
  created_at,
  updated_at,
  created_by_id,
  last_updated_by_id,
  from_sf,
  sf_id,
  is_deleted,
  deleted_at
) VALUES (
  :id,
  :submission_id,
  :observer_id,
  :trainer_id,
  :farmer_group_id,
  :training_session_id,
  :observation_date,
  :location_gps_latitude,
  :location_gps_longitude,
  :location_gps_altitude,
  :female_attendees,
  :male_attendees,
  :total_attendees,
  :comments,
  :observation_type,
  :created_at,
  :updated_at,
  :system_user,
  :system_user,
  TRUE,
  :sf_id,
  :is_deleted,
  :deleted_at
)
ON CONFLICT (sf_id) DO UPDATE SET
  submission_id          = EXCLUDED.submission_id,
  observer_id            = EXCLUDED.observer_id,
  trainer_id             = EXCLUDED.trainer_id,
  farmer_group_id        = EXCLUDED.farmer_group_id,
  training_session_id    = EXCLUDED.training_session_id,
  observation_date       = EXCLUDED.observation_date,
  location_gps_latitude  = EXCLUDED.location_gps_latitude,
  location_gps_longitude = EXCLUDED.location_gps_longitude,
  location_gps_altitude  = EXCLUDED.location_gps_altitude,
  female_attendees       = EXCLUDED.female_attendees,
  male_attendees         = EXCLUDED.male_attendees,
  total_attendees        = EXCLUDED.total_attendees,
  comments               = EXCLUDED.comments,
  observation_type       = EXCLUDED.observation_type,
  updated_at             = EXCLUDED.updated_at,
  last_updated_by_id     = EXCLUDED.last_updated_by_id,
  from_sf                = EXCLUDED.from_sf,
  is_deleted             = EXCLUDED.is_deleted,
  deleted_at             = EXCLUDED.deleted_at,
  sf_id                  = EXCLUDED.sf_id;
