INSERT INTO pima.training_sessions AS t (
  id, module_id, farmer_group_id,
  date_session_1, commcare_case_id,
  male_attendees_agg, female_attendees_agg, total_attendees_agg,
  send_to_commcare, created_at, updated_at,
  send_to_commcare_status,
  female_attendees_session_1, male_attendees_session_2, female_attendees_session_2,
  total_attendees_session_1, total_attendees_session_2,
  location_gps_latitude_session_1, location_gps_longitude_session_1, location_gps_altitude_session_1,
  location_gps_latitude_session_2, location_gps_longitude_session_2, location_gps_altitude_session_2,
  date_session_2,
  from_sf, sf_id,
  male_attendees_session_1,
  is_deleted, deleted_at,
  trainer_id, created_by_id, last_updated_by_id
) VALUES (
  :id, :module_id, :farmer_group_id,
  :date_session_1, :commcare_case_id,
  :male_attendees_agg, :female_attendees_agg, :total_attendees_agg,
  :send_to_commcare, :created_at, :updated_at,
  :send_to_commcare_status,
  :female_attendees_session_1, :male_attendees_session_2, :female_attendees_session_2,
  :total_attendees_session_1, :total_attendees_session_2,
  :lat1, :lon1, :alt1,
  :lat2, :lon2, :alt2,
  :date_session_2,
  TRUE, :sf_id,
  :male_attendees_session_1,
  :is_deleted, :deleted_at,
  :trainer_id, :system_user, :system_user
)
ON CONFLICT ON CONSTRAINT training_sessions_sf_id_key DO UPDATE SET
  module_id                     = EXCLUDED.module_id,
  farmer_group_id               = EXCLUDED.farmer_group_id,
  date_session_1                = EXCLUDED.date_session_1,
  commcare_case_id              = EXCLUDED.commcare_case_id,
  male_attendees_agg            = EXCLUDED.male_attendees_agg,
  female_attendees_agg          = EXCLUDED.female_attendees_agg,
  total_attendees_agg           = EXCLUDED.total_attendees_agg,
  send_to_commcare              = EXCLUDED.send_to_commcare,
  created_at                    = LEAST(t.created_at, EXCLUDED.created_at),
  updated_at                    = EXCLUDED.updated_at,
  send_to_commcare_status       = EXCLUDED.send_to_commcare_status,
  female_attendees_session_1    = EXCLUDED.female_attendees_session_1,
  male_attendees_session_2      = EXCLUDED.male_attendees_session_2,
  female_attendees_session_2    = EXCLUDED.female_attendees_session_2,
  total_attendees_session_1     = EXCLUDED.total_attendees_session_1,
  total_attendees_session_2     = EXCLUDED.total_attendees_session_2,
  location_gps_latitude_session_1  = EXCLUDED.location_gps_latitude_session_1,
  location_gps_longitude_session_1 = EXCLUDED.location_gps_longitude_session_1,
  location_gps_altitude_session_1  = EXCLUDED.location_gps_altitude_session_1,
  location_gps_latitude_session_2  = EXCLUDED.location_gps_latitude_session_2,
  location_gps_longitude_session_2 = EXCLUDED.location_gps_longitude_session_2,
  location_gps_altitude_session_2  = EXCLUDED.location_gps_altitude_session_2,
  date_session_2                = EXCLUDED.date_session_2,
  is_deleted                    = EXCLUDED.is_deleted,
  deleted_at                    = EXCLUDED.deleted_at,
  trainer_id                    = EXCLUDED.trainer_id,
  last_updated_by_id            = EXCLUDED.last_updated_by_id,
  from_sf                       = TRUE,
  sf_id                         = EXCLUDED.sf_id;
